### ISSUE TITLE
Server error when selecting 1988 for Trump candidate profile page

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3318]
**Thank you for your interest in helping improve the FEC CMS.**

Below, you'll find questions to help us more quickly identify, prioritize, and then address the issue.

### Summary

When clicking on 1988 for the Trump candidate profile page, I receive a server error page: 
https://www.fec.gov/data/candidate/P80001571/?cycle=1988&election_full=true

### Expected Behavior

A page should load, or 1988 shouldn't be in the dropdown

### Actual Behavior

Server error

### Frequency

- [X] This is an ongoing, predictable issue

### How to Reproduce

1. Go to https://www.fec.gov/data/candidate/P80001571/
2. Select 1988 from the years dropdown

### Browser

_Which version of which browser are you using? Does this issue occur with other browsers or with other browser sizes?_

- [X] Chrome

### Device

_Tell us what you can about your device and its operating system._

- [X] Laptop/desktop (PC/Windows)

### Screenshots

![Capture](https://user-images.githubusercontent.com/31420082/68089595-7e2cce00-fe38-11e9-8d4f-1f0d25534317.JPG)

**Comment by pkfec** [comment]
I tried to reproduce on my local and here is the error log stack trace:

2019-11-03T19:42:46.70-0500 [APP/PROC/WEB/0] ERR INFO:data.api_caller: load_first_row_data: https://fec-dev-api.app.cloud.gov/v1/committee/C00354761/history?per_page=1&api_key=aA4PfxHH07ra3QDSYutq5QjCFga62aneCGqGHENt
   2019-11-03T19:42:46.72-0500 [APP/PROC/WEB/0] ERR INFO:data.api_caller: load_endpoint_result: https://fec-dev-api.app.cloud.gov/v1/committee/C00354761/candidates/history/None?election_full=false&api_key=aA4PfxHH07ra3QDSYutq5QjCFga62aneCGqGHENt
   2019-11-03T19:42:46.72-0500 [APP/PROC/WEB/0] ERR ERROR:data.api_caller: API ERROR with status 404 for https://fec-dev-api.app.cloud.gov/v1/committee/C00354761/candidates/history/None with filters: {'election_full': 'false', 'api_key': 'aA4PfxHH07ra3QDSYutq5QjCFga62aneCGqGHENt'}
   2019-11-03T19:42:46.75-0500 [APP/PROC/WEB/0] ERR ERROR:django.request: Internal Server Error: /data/committee/C00354761/
   2019-11-03T19:42:46.75-0500 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2019-11-03T19:42:46.75-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
   2019-11-03T19:42:46.75-0500 [APP/PROC/WEB/0] ERR     response = get_response(request)
   2019-11-03T19:42:46.75-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
   2019-11-03T19:42:46.75-0500 [APP/PROC/WEB/0] ERR     response = self._get_response(request)
   2019-11-03T19:42:46.75-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
   2019-11-03T19:42:46.75-0500 [APP/PROC/WEB/0] ERR     response = self.process_exception_by_middleware(e, request)
   2019-11-03T19:42:46.75-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
   2019-11-03T19:42:46.75-0500 [APP/PROC/WEB/0] ERR     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   2019-11-03T19:42:46.75-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/app/fec/data/views.py", line 523, in committee
   **2019-11-03T19:42:46.75-0500 [APP/PROC/WEB/0] ERR     committee = get_committee(committee_id, cycle)**
   **2019-11-03T19:42:46.75-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/app/fec/data/views.py", line 353, in get_committee
   2019-11-03T19:42:46.75-0500 [APP/PROC/WEB/0] ERR     cycle = int(cycle)
   2019-11-03T19:42:46.75-0500 [APP/PROC/WEB/0] ERR TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'**

**Comment by JonellaCulmer** [comment]
Merged, so closing.
