### ISSUE TITLE
Feedback box not working

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3572]
### Summary

Feedback box not working in `production`

### Expected Behavior

Go to www.fec.gov, submit issue through feedback box, issue is created in fecgov/FEC repo

### Actual Behavior

Error

<img width="1439" alt="Screen Shot 2020-02-25 at 11 27 59 AM" src="https://user-images.githubusercontent.com/31420082/75268502-9187ee80-57c5-11ea-817b-a90455718b18.png">

```
   2020-02-25T11:31:58.85-0500 [APP/PROC/WEB/3] ERR ERROR:django.request: Internal Server Error: /data/issue/
   2020-02-25T11:31:58.85-0500 [APP/PROC/WEB/3] ERR Traceback (most recent call last):
   2020-02-25T11:31:58.85-0500 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
   2020-02-25T11:31:58.85-0500 [APP/PROC/WEB/3] ERR     response = get_response(request)
   2020-02-25T11:31:58.85-0500 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
   2020-02-25T11:31:58.85-0500 [APP/PROC/WEB/3] ERR     response = self._get_response(request)
   2020-02-25T11:31:58.85-0500 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
   2020-02-25T11:31:58.85-0500 [APP/PROC/WEB/3] ERR     response = self.process_exception_by_middleware(e, request)
   2020-02-25T11:31:58.85-0500 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
   2020-02-25T11:31:58.85-0500 [APP/PROC/WEB/3] ERR     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   2020-02-25T11:31:58.85-0500 [APP/PROC/WEB/3] ERR   File "/home/vcap/app/fec/data/views.py", line 733, in feedback
   2020-02-25T11:31:58.85-0500 [APP/PROC/WEB/3] ERR     title, body=body
   2020-02-25T11:31:58.85-0500 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/github3/decorators.py", line 38, in auth_wrapper
   2020-02-25T11:31:58.85-0500 [APP/PROC/WEB/3] ERR     return func(self, *args, **kwargs)
   2020-02-25T11:31:58.85-0500 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/github3/repos/repo.py", line 650, in create_issue
   2020-02-25T11:31:58.85-0500 [APP/PROC/WEB/3] ERR     json = self._json(self._post(url, data=issue), 201)
   2020-02-25T11:31:58.85-0500 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/github3/models.py", line 100, in _json
   2020-02-25T11:31:58.85-0500 [APP/PROC/WEB/3] ERR     if self._boolean(response, status_code, 404) and response.content:
   2020-02-25T11:31:58.85-0500 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.6/site-packages/github3/models.py", line 121, in _boolean
   2020-02-25T11:31:58.85-0500 [APP/PROC/WEB/3] ERR     raise GitHubError(response)
   2020-02-25T11:31:58.85-0500 [APP/PROC/WEB/3] ERR github3.models.GitHubError: 500 [No message]
```

### Frequency

- @PaulClark2 was able to submit feedback yesterday when this was reported, so it's not reproducible every time

I believe this is being caused by Github errors, reported here: https://www.githubstatus.com/incidents/xp2qc958g4wt

**Comment by lbeaufort** [comment]
We can probably monitor the errors here: https://www.githubstatus.com/incidents/xp2qc958g4wt and re-check once they've been resolved.

**Comment by PaulClark2** [comment]
An issues with the feedback box was reported yesterday. I could not replicate the error. I tested three browsers.

https://github.com/fecgov/FEC/issues/9538
https://github.com/fecgov/FEC/issues/9539
https://github.com/fecgov/FEC/issues/9540

**Comment by PaulClark2** [comment]
Cannot replicate, so closing.
