### ISSUE TITLE
Fix home page server error 

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#4462]
<img width="1055" alt="Screen Shot 2021-03-09 at 1 42 34 PM" src="https://user-images.githubusercontent.com/31420082/110521094-54934f00-80dd-11eb-9248-f06ad6f2eb55.png">

https://stage.fec.gov/ and https://dev.fec.gov/ home pages get a server error. 

CMS logs: 
```
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR INFO:django.request: OK: /
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR     response = get_response(request)
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 145, in _get_response
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR     response = self.process_exception_by_middleware(e, request)
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 143, in _get_response
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR     response = response.render()
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/response.py", line 106, in render
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR     self.content = self.rendered_content
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/response.py", line 83, in rendered_content
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR     content = template.render(context, self._request)
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR     return self.template.render(context)
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 171, in render
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR     return self._render(context)
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR     return self.nodelist.render(context)
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 937, in render
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR     bit = node.render_annotated(context)
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR     return self.render(context)
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/loader_tags.py", line 127, in render
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR     compiled_parent = self.get_parent(context)
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/loader_tags.py", line 124, in get_parent
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR     return self.find_template(parent, context)
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/loader_tags.py", line 104, in find_template
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR     template_name, skip=history,
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/engine.py", line 125, in find_template
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR     template = loader.get_template(name, skip=skip)
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/loaders/base.py", line 30, in get_template
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR     contents, origin, origin.template_name, self.engine,
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 156, in __init__
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR     self.nodelist = self.compile_nodelist()
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 194, in compile_nodelist
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR     return parser.parse()
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 478, in parse
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR     raise self.error(token, e)
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 476, in parse
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR     compiled_result = compile_func(self, token)
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/loader_tags.py", line 316, in do_include
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR     return IncludeNode(parser.compile_filter(bits[1]), extra_context=namemap,
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 563, in compile_filter
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR     return FilterExpression(token, self)
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 663, in __init__
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR     "from '%s'" % (token[upto:], token))
   2021-03-09T13:32:40.84-0500 [APP/PROC/WEB/0] ERR django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''partials/meta-tags-preloads.html' from ''partials/meta-tags-preloads.html'
   ```

**Comment by lbeaufort** [comment]
PR's merged to release and develop branches.
