### ISSUE TITLE
Some site-wide searches producing a server error message

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#4491]
### Summary

When trying to search on the site for "new form 2," an error message comes up

### How to Reproduce

Search "new form 2" in the search bar on the site

### Device, browser, etc

- Tried in Chrome, Firefox, and Edge

### Screenshots

![image](https://user-images.githubusercontent.com/40633757/111527437-50e37600-8736-11eb-81c5-0b088126325b.png)

**Comment by dorothyyeager** [comment]
Screenshot when quotes were added around "new form 2" - search worked, but we don't want to make users do this.
![image](https://user-images.githubusercontent.com/24437369/111528184-365dcc80-8737-11eb-9862-e10e5db78d36.png)

**Comment by lbeaufort** [comment]
From the logs: 
```
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR INFO:django.request: OK: /search/
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR Traceback (most recent call last):
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     response = get_response(request)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     response = self.process_exception_by_middleware(e, request)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/app/fec/search/views.py", line 139, in search
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     'self': {'title': 'Search results'}
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     content = loader.render_to_string(template_name, context, request, using=using)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     return template.render(context, request)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     return self.template.render(context)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 171, in render
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     return self._render(context)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     return self.nodelist.render(context)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 937, in render
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     bit = node.render_annotated(context)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     return self.render(context)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     return compiled_parent._render(context)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     return self.nodelist.render(context)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 937, in render
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     bit = node.render_annotated(context)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     return self.render(context)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     result = block.nodelist.render(context)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 937, in render
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     bit = node.render_annotated(context)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     return self.render(context)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/defaulttags.py", line 309, in render
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     return nodelist.render(context)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 937, in render
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     bit = node.render_annotated(context)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     return self.render(context)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/defaulttags.py", line 309, in render
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     return nodelist.render(context)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 937, in render
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     bit = node.render_annotated(context)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     return self.render(context)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/defaulttags.py", line 209, in render
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     nodelist.append(node.render_annotated(context))
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     return self.render(context)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 987, in render
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     output = self.filter_expression.resolve(context)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/template/base.py", line 698, in resolve
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     new_obj = func(obj, *arg_vals)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/app/fec/home/templatetags/filters.py", line 73, in highlight_matches
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     return format_html(highlighted_text)
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR   File "/home/vcap/deps/0/python/lib/python3.7/site-packages/django/utils/html.py", line 118, in format_html
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR     return mark_safe(format_string.format(*args_safe, **kwargs_safe))
   2021-03-17T15:52:12.13-0400 [APP/PROC/WEB/3] ERR ValueError: expected '}' before end of string
   ```

**Comment by lbeaufort** [comment]
the `mark_safe` function here :`return mark_safe(format_string.format(*args_safe, **kwargs_safe))` is using `str.format`, for which curly braces are a special character. 

see  https://docs.python.org/3/library/string.html#formatstrings

I think our best option is to remove `{` and `}` from results. I think we should start by adding automated tests.

**Comment by lbeaufort** [comment]
There have been about 55 examples of this error in production. 

**Example errors:** 
https://www.fec.gov/search/?type=candidates&type=committees&type=site&query=field+name+%2318
```
KeyError: 'Contributor First <span class="t-highlight">Name</span>'
```

https://www.fec.gov/search/?type=candidates&type=committees&type=site&query=Micellaneous+text+submission
```
ValueError: Single '}' encountered in format string
```

**Comment by lbeaufort** [comment]
Thank you @djgarr for catching this! A fix has been deployed: https://www.fec.gov/search/?type=candidates&type=committees&type=site&query=new+form+2
